# Default data for Config Editor tabs.
# Replace these lists with your actual data — each entry is a tuple of strings.
# Sector Stock: (Sector, Stock)
# Script Name:  (Stock, Initial)
# Main Column Name: (Actual, Renamed)
# Main Column Order: (Column Name,)  — single column, reorderable

SECTOR_STOCK_DATA = [
    ('INDEX', 'NIFTY'),
    ('INDEX', 'BANKNIFTY'),
    ('INDEX', 'FINNIFTY'),
    ('INDEX', 'MIDCPNIFTY'),
    ('FINANCE', '360ONE'),
    ('CG', 'ABB'),
    ('FINANCE', 'ABCAPITAL'),
    ('POWER', 'ADANIENSOL'),
    ('INFRA', 'ADANIENT'),
    ('POWER', 'ADANIGREEN'),
    ('INFRA', 'ADANIPORTS'),
    ('PHARMA', 'ALKEM'),
    ('CG', 'AMBER'),
    ('CEMENT', 'AMBUJACEM'),
    ('FINANCE', 'ANGELONE'),
    ('METALS', 'APLAPOLLO'),
    ('PHARMA', 'APOLLOHOSP'),
    ('AUTO', 'ASHOKLEY'),
    ('FMCG', 'ASIANPAINT'),
    ('CG', 'ASTRAL'),
    ('BANKING', 'AUBANK'),
    ('PHARMA', 'AUROPHARMA'),
    ('BANKING', 'AXISBANK'),
    ('AUTO', 'BAJAJ-AUTO'),
    ('FINANCE', 'BAJAJFINSV'),
    ('FINANCE', 'BAJFINANCE'),
    ('BANKING', 'BANDHANBNK'),
    ('BANKING', 'BANKBARODA'),
    ('BANKING', 'BANKINDIA'),
    ('CG', 'BDL'),
    ('CG', 'BEL'),
    ('AUTO', 'BHARATFORG'),
    ('TELECOM', 'BHARTIARTL'),
    ('CG', 'BHEL'),
    ('PHARMA', 'BIOCON'),
    ('CG', 'BLUESTARCO'),
    ('AUTO', 'BOSCHLTD'),
    ('OIL&GAS', 'BPCL'),
    ('FMCG', 'BRITANNIA'),
    ('FINANCE', 'BSE'),
    ('FINANCE', 'CAMS'),
    ('BANKING', 'CANBK'),
    ('FINANCE', 'CDSL'),
    ('POWER', 'CGPOWER'),
    ('FINANCE', 'CHOLAFIN'),
    ('PHARMA', 'CIPLA'),
    ('METALS', 'COALINDIA'),
    ('TECHNOLOGY', 'COFORGE'),
    ('FMCG', 'COLPAL'),
    ('INFRA', 'CONCOR'),
    ('CG', 'CROMPTON'),
    ('CG', 'CUMMINSIND'),
    ('FMCG', 'DABUR'),
    ('CEMENT', 'DALBHARAT'),
    ('NEW AGE', 'DELHIVERY'),
    ('PHARMA', 'DIVISLAB'),
    ('CG', 'DIXON'),
    ('REALTY', 'DLF'),
    ('NEW AGE', 'DMART'),
    ('PHARMA', 'DRREDDY'),
    ('AUTO', 'EICHERMOT'),
    ('NEW AGE', 'ETERNAL'),
    ('AUTO', 'EXIDEIND'),
    ('BANKING', 'FEDERALBNK'),
    ('PHARMA', 'FORTIS'),
    ('OIL&GAS', 'GAIL'),
    ('PHARMA', 'GLENMARK'),
    ('INFRA', 'GMRAIRPORT'),
    ('FMCG', 'GODREJCP'),
    ('REALTY', 'GODREJPROP'),
    ('CEMENT', 'GRASIM'),
    ('CG', 'HAL'),
    ('CG', 'HAVELLS'),
    ('TECHNOLOGY', 'HCLTECH'),
    ('FINANCE', 'HDFCAMC'),
    ('BANKING', 'HDFCBANK'),
    ('FINANCE', 'HDFCLIFE'),
    ('AUTO', 'HEROMOTOCO'),
    ('METALS', 'HINDALCO'),
    ('OIL&GAS', 'HINDPETRO'),
    ('FMCG', 'HINDUNILVR'),
    ('METALS', 'HINDZINC'),
    ('BANKING', 'ICICIBANK'),
    ('FINANCE', 'ICICIGI'),
    ('FINANCE', 'ICICIPRULI'),
    ('TELECOM', 'IDEA'),
    ('BANKING', 'IDFCFIRSTB'),
    ('POWER', 'IEX'),
    ('REALTY', 'INDHOTEL'),
    ('BANKING', 'INDIANB'),
    ('INFRA', 'INDIGO'),
    ('BANKING', 'INDUSINDBK'),
    ('TELECOM', 'INDUSTOWER'),
    ('TECHNOLOGY', 'INFY'),
    ('POWER', 'INOXWIND'),
    ('OIL&GAS', 'IOC'),
    ('FINANCE', 'IREDA'),
    ('INFRA', 'IRFC'),
    ('FMCG', 'ITC'),
    ('METALS', 'JINDALSTEL'),
    ('FINANCE', 'JIOFIN'),
    ('POWER', 'JSWENERGY'),
    ('METALS', 'JSWSTEEL'),
    ('FMCG', 'JUBLFOOD'),
    ('FMCG', 'KALYANKJIL'),
    ('CG', 'KAYNES'),
    ('POWER', 'KEI'),
    ('FINANCE', 'KFINTECH'),
    ('BANKING', 'KOTAKBANK'),
    ('TECHNOLOGY', 'KPITTECH'),
    ('PHARMA', 'LAURUSLABS'),
    ('FINANCE', 'LICHSGFIN'),
    ('FINANCE', 'LICI'),
    ('REALTY', 'LODHA'),
    ('CG', 'LT'),
    ('FINANCE', 'LTF'),
    ('TECHNOLOGY', 'LTIM'),
    ('PHARMA', 'LUPIN'),
    ('AUTO', 'M&M'),
    ('FINANCE', 'MANAPPURAM'),
    ('PHARMA', 'MANKIND'),
    ('FMCG', 'MARICO'),
    ('AUTO', 'MARUTI'),
    ('PHARMA', 'MAXHEALTH'),
    ('INFRA', 'MAZDOCK'),
    ('FINANCE', 'MCX'),
    ('FINANCE', 'MFSL'),
    ('AUTO', 'MOTHERSON'),
    ('TECHNOLOGY', 'MPHASIS'),
    ('FINANCE', 'MUTHOOTFIN'),
    ('METALS', 'NATIONALUM'),
    ('NEW AGE', 'NAUKRI'),
    ('REALTY', 'NBCC'),
    ('FMCG', 'NESTLEIND'),
    ('POWER', 'NHPC'),
    ('METALS', 'NMDC'),
    ('POWER', 'NTPC'),
    ('FINANCE', 'NUVAMA'),
    ('NEW AGE', 'NYKAA'),
    ('REALTY', 'OBEROIRLTY'),
    ('TECHNOLOGY', 'OFSS'),
    ('OIL&GAS', 'OIL'),
    ('OIL&GAS', 'ONGC'),
    ('TEXTILES', 'PAGEIND'),
    ('FMCG', 'PATANJALI'),
    ('NEW AGE', 'PAYTM'),
    ('TECHNOLOGY', 'PERSISTENT'),
    ('OIL&GAS', 'PETRONET'),
    ('FINANCE', 'PFC'),
    ('CG', 'PGEL'),
    ('REALTY', 'PHOENIXLTD'),
    ('FMCG', 'PIDILITIND'),
    ('CHEMICALS', 'PIIND'),
    ('BANKING', 'PNB'),
    ('FINANCE', 'PNBHOUSING'),
    ('NEW AGE', 'POLICYBZR'),
    ('CG', 'POLYCAB'),
    ('POWER', 'POWERGRID'),
    ('REALTY', 'PRESTIGE'),
    ('BANKING', 'RBLBANK'),
    ('FINANCE', 'RECLTD'),
    ('OIL&GAS', 'RELIANCE'),
    ('INFRA', 'RVNL'),
    ('METALS', 'SAIL'),
    ('FINANCE', 'SBICARD'),
    ('FINANCE', 'SBILIFE'),
    ('BANKING', 'SBIN'),
    ('CEMENT', 'SHREECEM'),
    ('FINANCE', 'SHRIRAMFIN'),
    ('CG', 'SIEMENS'),
    ('POWER', 'SOLARINDS'),
    ('AUTO', 'SONACOMS'),
    ('TEXTILES', 'SRF'),
    ('PHARMA', 'SUNPHARMA'),
    ('CG', 'SUPREMEIND'),
    ('POWER', 'SUZLON'),
    ('FMCG', 'TATACONSUM'),
    ('TECHNOLOGY', 'TATAELXSI'),
    ('AUTO', 'TMPV'),
    ('POWER', 'TATAPOWER'),
    ('METALS', 'TATASTEEL'),
    ('TECHNOLOGY', 'TCS'),
    ('TECHNOLOGY', 'TECHM'),
    ('CG', 'TIINDIA'),
    ('FMCG', 'TITAN'),
    ('PHARMA', 'TORNTPHARM'),
    ('TEXTILES', 'TRENT'),
    ('AUTO', 'TVSMOTOR'),
    ('CEMENT', 'ULTRACEMCO'),
    ('BANKING', 'UNIONBANK'),
    ('FMCG', 'UNITDSPR'),
    ('AUTO', 'UNOMINDA'),
    ('CHEMICALS', 'UPL'),
    ('FMCG', 'VBL'),
    ('METALS', 'VEDL'),
    ('CG', 'VOLTAS'),
    ('TECHNOLOGY', 'WIPRO'),
    ('BANKING', 'YESBANK'),
    ('PHARMA', 'ZYDUSLIFE'),
    ('POWER', 'ADANIPOWER'),
    ('FINANCE', 'BAJAJHLDNG'),
    ('INFRA', 'COCHINSHIP'),
    ('AUTO', 'FORCEMOT'),
    ('OTHERS', 'GVT&D'),
    ('FMCG', 'GODFRYPHLP'),
    ('CG', 'POWERINDIA'),
    ('AUTO', 'HYUNDAI'),
    ('FINANCE', 'MOTILALOFS'),
    ('INDEX', 'NIFTYNXT50'),
    ('FINANCE', 'NAM-INDIA'),
    ('CG', 'PREMIERENE'),
    ('OTHERS', 'RADICO'),
    ('FINANCE', 'SAMMAANCAP'),
    ('NEW AGE', 'SWIGGY'),
    ('NEW AGE', 'VMM'),
    ('CG', 'WAAREEENER'),
]

SCRIPT_NAME_DATA = [
    ('360 ONE WAM LIMITED.rolling.12D', '360ONE'),
    ('ABB LTD.rolling.12D', 'ABB'),
    ('ADANI ENERGY SOLUTIONS L.rolling.12D', 'ADANIENSOL'),
    ('ADANI GREEN ENERGY LIMIT.rolling.12D', 'ADANIGREEN'),
    ('ADANIENT.rolling.12D', 'ADANIENT'),
    ('ADANIPORT.rolling.12D', 'ADANIPORTS'),
    ('ADANIPOWER.rolling.12D', 'ADANIPOWER'),
    ('ADITYA BIRLA CAPITAL LIM.rolling.12D', 'ABCAPITAL'),
    ('ALKEM.rolling.12D', 'ALKEM'),
    ('AMBER ENTERPRISES INDIA.rolling.12D', 'AMBER'),
    ('Ambuja Cements Ltd.rolling.12D', 'AMBUJACEM'),
    ('ANGEL ONE LIMITED.rolling.12D', 'ANGELONE'),
    ('APL APOLLO TUBES LIMITED.rolling.12D', 'APLAPOLLO'),
    ('APOLLOHOSP.rolling.12D', 'APOLLOHOSP'),
    ('ASHOKLEY.rolling.12D', 'ASHOKLEY'),
    ('ASIAN PAINTS LIMITED.rolling.12D', 'ASIANPAINT'),
    ('ASTRAL.rolling.12D', 'ASTRAL'),
    ('AU SMALL FINANCE BANK LI.rolling.12D', 'AUBANK'),
    ('AUROPHARMA.rolling.12D', 'AUROPHARMA'),
    ('AVENUE SUPERMARTS LIMITE.rolling.12D', 'DMART'),
    ('AXISBANK.rolling.12D', 'AXISBANK'),
    ('Bajaj Auto Limited.rolling.12D', 'BAJAJ-AUTO'),
    ('BAJAJ HOLDINGS & INVESTM.rolling.12D', 'BAJAJHLDNG'),
    ('BAJAJFINSV.rolling.12D', 'BAJAJFINSV'),
    ('BAJFINANCE.rolling.12D', 'BAJFINANCE'),
    ('BANDHANBNK.rolling.12D', 'BANDHANBNK'),
    ('BANK OF INDIA.rolling.12D', 'BANKINDIA'),
    ('BANKBARODA.rolling.12D', 'BANKBARODA'),
    ('BANKNIFTY.rolling.12D', 'BANKNIFTY'),
    ('Bharat Dynamics Limited.rolling.12D', 'BDL'),
    ('Bharat Electronics Limit.rolling.12D', 'BEL'),
    ('BHARATFORG.rolling.12D', 'BHARATFORG'),
    ('BHARTIARTL.rolling.12D', 'BHARTIARTL'),
    ('BHEL.rolling.12D', 'BHEL'),
    ('BIOCON LIMITED..rolling.12D', 'BIOCON'),
    ('BLUE STAR LIMITED.rolling.12D', 'BLUESTARCO'),
    ('Bosch Limited.rolling.12D', 'BOSCHLTD'),
    ('BPCL.rolling.12D', 'BPCL'),
    ('BRITANNIA.rolling.12D', 'BRITANNIA'),
    ('BSE LIMITED.rolling.12D', 'BSE'),
    ('CANBK.rolling.12D', 'CANBK'),
    ('CDSL.rolling.12D', 'CDSL'),
    ('CG POWER AND INDUSTRIAL.rolling.12D', 'CGPOWER'),
    ('CHOLAFIN.rolling.12D', 'CHOLAFIN'),
    ('CIPLA.rolling.12D', 'CIPLA'),
    ('COAL INDIA LIMITED.rolling.12D', 'COALINDIA'),
    ('COCHINSHIP.rolling.12D', 'COCHINSHIP'),
    ('COFORGE LIMITED.rolling.12D', 'COFORGE'),
    ('Colgate Palmolive (India.rolling.12D', 'COLPAL'),
    ('COMPUTER AGE MANAGEMENT.rolling.12D', 'CAMS'),
    ('CONTAINER CORPORATION OF.rolling.12D', 'CONCOR'),
    ('CROMPTON GREAVES CONSUME.rolling.12D', 'CROMPTON'),
    ('CUMMINSIND.rolling.12D', 'CUMMINSIND'),
    ('DABUR.rolling.12D', 'DABUR'),
    ('DALMIA BHARAT LIMITED.rolling.12D', 'DALBHARAT'),
    ('DELHIVERY LIMITED.rolling.12D', 'DELHIVERY'),
    ('DIVISLAB.rolling.12D', 'DIVISLAB'),
    ('DIXON.rolling.12D', 'DIXON'),
    ('DLF Limited.rolling.12D', 'DLF'),
    ('DRREDDY.rolling.12D', 'DRREDDY'),
    ('EICHERMOT.rolling.12D', 'EICHERMOT'),
    ('ETERNAL LIMITED.rolling.12D', 'ETERNAL'),
    ('EXIDE INDUSTRIES LTD.rolling.12D', 'EXIDEIND'),
    ('FEDERALBNK.rolling.12D', 'FEDERALBNK'),
    ('FINNIFTY.rolling.12D', 'FINNIFTY'),
    ('FORCEMOT.rolling.12D', 'FORCEMOT'),
    ('Fortis Healthcare Limite.rolling.12D', 'FORTIS'),
    ('FSN E-COMMERCE VENTURES.rolling.12D', 'NYKAA'),
    ('GAIL.rolling.12D', 'GAIL'),
    ('GE Vernova T&D India Lim.rolling.12D', 'GVT&D'),
    ('GLENMARK PHARMACEUTICALS.rolling.12D', 'GLENMARK'),
    ('GMR AIRPORTS LIMITED.rolling.12D', 'GMRAIRPORT'),
    ('GODFRYPHLP.rolling.12D', 'GODFRYPHLP'),
    ('GODREJ CONSUMER PRODUCTS.rolling.12D', 'GODREJCP'),
    ('GODREJPROP.rolling.12D', 'GODREJPROP'),
    ('GRASIM INDUSTRIES LIMITE.rolling.12D', 'GRASIM'),
    ('HAL.rolling.12D', 'HAL'),
    ('HAVELLS INDIA LIMITED.rolling.12D', 'HAVELLS'),
    ('HCLTECH.rolling.12D', 'HCLTECH'),
    ('HDFC Asset Management Co.rolling.12D', 'HDFCAMC'),
    ('HDFCBANK.rolling.12D', 'HDFCBANK'),
    ('HDFCLIFE.rolling.12D', 'HDFCLIFE'),
    ('HEROMOTOCO.rolling.12D', 'HEROMOTOCO'),
    ('HINDALCO.rolling.12D', 'HINDALCO'),
    ('HINDPETRO.rolling.12D', 'HINDPETRO'),
    ('Hindustan Unilever Limit.rolling.12D', 'HINDUNILVR'),
    ('HINDUSTAN ZINC LIMITED.rolling.12D', 'HINDZINC'),
    ('HITACHI ENERGY INDIA LIM.rolling.12D', 'POWERINDIA'),
    ('HYUNDAI.rolling.12D', 'HYUNDAI'),
    ('ICICI Lombard General In.rolling.12D', 'ICICIGI'),
    ('ICICIBANK.rolling.12D', 'ICICIBANK'),
    ('ICICIPRULI.rolling.12D', 'ICICIPRULI'),
    ('Idea Cellular Ltd..rolling.12D', 'IDEA'),
    ('IDFC First Bank Limited.rolling.12D', 'IDFCFIRSTB'),
    ('IEX.rolling.12D', 'IEX'),
    ('INDHOTEL.rolling.12D', 'INDHOTEL'),
    ('INDIAN BANK.rolling.12D', 'INDIANB'),
    ('INDIAN RAILWAY FINANCE C.rolling.12D', 'IRFC'),
    ('INDIAN RENEWABLE ENERGY.rolling.12D', 'IREDA'),
    ('INDIGO.rolling.12D', 'INDIGO'),
    ('INDUS TOWERS LIMITED.rolling.12D', 'INDUSTOWER'),
    ('INDUSIND BANK LIMITED.rolling.12D', 'INDUSINDBK'),
    ('Infosys Limited.rolling.12D', 'INFY'),
    ('Inox Wind Limited.rolling.12D', 'INOXWIND'),
    ('IOC.rolling.12D', 'IOC'),
    ('ITC.rolling.12D', 'ITC'),
    ('Jindal Steel & Power Lim.rolling.12D', 'JINDALSTEL'),
    ('JIO FINANCIAL SERVICES L.rolling.12D', 'JIOFIN'),
    ('JSW ENERGY LIMITED.rolling.12D', 'JSWENERGY'),
    ('JSW STEEL LIMITED.rolling.12D', 'JSWSTEEL'),
    ('JUBILANT FOODWORKS LTD.rolling.12D', 'JUBLFOOD'),
    ('KALYAN JEWELLERS INDIA L.rolling.12D', 'KALYANKJIL'),
    ('Kaynes Technology India.rolling.12D', 'KAYNES'),
    ('KEI INDUSTRIES LIMITED.rolling.12D', 'KEI'),
    ('KFIN TECHNOLOGIES LIMITE.rolling.12D', 'KFINTECH'),
    ('KOTAK MAHINDRA BANK LTD.rolling.12D', 'KOTAKBANK'),
    ('KPIT TECHNOLOGIES LIMITE.rolling.12D', 'KPITTECH'),
    ('L&T FINANCE LIMITED.rolling.12D', 'LTF'),
    ('Larsen & Toubro Ltd.rolling.12D', 'LT'),
    ('Laurus Labs Limited.rolling.12D', 'LAURUSLABS'),
    ('LICHSGFIN.rolling.12D', 'LICHSGFIN'),
    ('LIFE INSURANCE CORPORATI.rolling.12D', 'LICI'),
    ('LTM LIMITED.rolling.12D', 'LTIM'),
    ('LUPIN LIMITED.rolling.12D', 'LUPIN'),
    ('M&M.rolling.12D', 'M&M'),
    ('MACROTECH DEVELOPERS LIM.rolling.12D', 'LODHA'),
    ('MANAPPURAM.rolling.12D', 'MANAPPURAM'),
    ('Mankind Pharma Limited.rolling.12D', 'MANKIND'),
    ('MARICO LIMITED.rolling.12D', 'MARICO'),
    ('Maruti Suzuki India Ltd.rolling.12D', 'MARUTI'),
    ('MAX FINANCIAL SERVICES L.rolling.12D', 'MFSL'),
    ('MAX HEALTHCARE INSTITUTE.rolling.12D', 'MAXHEALTH'),
    ('Mazagon Dock Shipbuilder.rolling.12D', 'MAZDOCK'),
    ('MCX.rolling.12D', 'MCX'),
    ('MIDCPNIFTY.rolling.12D', 'MIDCPNIFTY'),
    ('MOTHERSON.rolling.12D', 'MOTHERSON'),
    ('MOTILALOFS.rolling.12D', 'MOTILALOFS'),
    ('MphasiS Limited.rolling.12D', 'MPHASIS'),
    ('MUTHOOTFIN.rolling.12D', 'MUTHOOTFIN'),
    ('NATIONALUM.rolling.12D', 'NATIONALUM'),
    ('NAUKRI.rolling.12D', 'NAUKRI'),
    ('NBCC.rolling.12D', 'NBCC'),
    ('NESTLEIND.rolling.12D', 'NESTLEIND'),
    ('NHPC LIMITED.rolling.12D', 'NHPC'),
    ('NIFTY.rolling.12D', 'NIFTY'),
    ('NIFTYNXT50.rolling.12D', 'NIFTYNXT50'),
    ('NIPPON LIFE INDIA ASSET.rolling.12D', 'NAM-INDIA'),
    ('NMDC LTD..rolling.12D', 'NMDC'),
    ('NTPC.rolling.12D', 'NTPC'),
    ('NUVAMA.rolling.12D', 'NUVAMA'),
    ('Oberoi Realty Limited.rolling.12D', 'OBEROIRLTY'),
    ('OFSS.rolling.12D', 'OFSS'),
    ('OIL INDIA LIMITED.rolling.12D', 'OIL'),
    ('ONE 97 COMMUNICATIONS LI.rolling.12D', 'PAYTM'),
    ('ONGC.rolling.12D', 'ONGC'),
    ('PAGEIND.rolling.12D', 'PAGEIND'),
    ('PATANJALI FOODS LIMITED.rolling.12D', 'PATANJALI'),
    ('PB FINTECH LIMITED.rolling.12D', 'POLICYBZR'),
    ('PERSISTENT.rolling.12D', 'PERSISTENT'),
    ('PETRONET LNG LIMITED.rolling.12D', 'PETRONET'),
    ('PG ELECTROPLAST LIMITED.rolling.12D', 'PGEL'),
    ('PI Industries Limited.rolling.12D', 'PIIND'),
    ('PIDILITIND.rolling.12D', 'PIDILITIND'),
    ('PNB HOUSING FINANCE LIMI.rolling.12D', 'PNBHOUSING'),
    ('PNB.rolling.12D', 'PNB'),
    ('POLYCAB.rolling.12D', 'POLYCAB'),
    ('Power Finance Corporatio.rolling.12D', 'PFC'),
    ('Power Grid Corporation o.rolling.12D', 'POWERGRID'),
    ('PREMIERENE.rolling.12D', 'PREMIERENE'),
    ('PRESTIGE ESTATES PROJECT.rolling.12D', 'PRESTIGE'),
    ('Radico Khaitan Limited.rolling.12D', 'RADICO'),
    ('Rail Vikas Nigam Limited.rolling.12D', 'RVNL'),
    ('RBLBANK.rolling.12D', 'RBLBANK'),
    ('REC LIMITED.rolling.12D', 'RECLTD'),
    ('RELIANCE.rolling.12D', 'RELIANCE'),
    ('SAMMAAN CAPITAL LIMITED.rolling.12D', 'SAMMAANCAP'),
    ('SBICARD.rolling.12D', 'SBICARD'),
    ('SBILIFE.rolling.12D', 'SBILIFE'),
    ('SBIN.rolling.12D', 'SBIN'),
    ('Shree Cements Ltd..rolling.12D', 'SHREECEM'),
    ('Shriram Finance Limited.rolling.12D', 'SHRIRAMFIN'),
    ('SIEMENS.rolling.12D', 'SIEMENS'),
    ('Solar Industries India L.rolling.12D', 'SOLARINDS'),
    ('SONA BLW PRECISION FORGI.rolling.12D', 'SONACOMS'),
    ('SRF.rolling.12D', 'SRF'),
    ('Steel Authority of India.rolling.12D', 'SAIL'),
    ('SUNPHARMA.rolling.12D', 'SUNPHARMA'),
    ('SUPREMEINDUSTRIES LIMIT.rolling.12D', 'SUPREMEIND'),
    ('SUZLON ENERGY LIMITED.rolling.12D', 'SUZLON'),
    ('SWIGGY.rolling.12D', 'SWIGGY'),
    ('TATA CONSUMER PRODUCTS L.rolling.12D', 'TATACONSUM'),
    ('TATA ELXSI LIMITED.rolling.12D', 'TATAELXSI'),
    ('TATA MOTORS PASS VEH LTD.rolling.12D', 'TMPV'),
    ('TATAPOWER.rolling.12D', 'TATAPOWER'),
    ('TATASTEEL.rolling.12D', 'TATASTEEL'),
    ('TCS.rolling.12D', 'TCS'),
    ('TECH MAHINDRA LIMITED.rolling.12D', 'TECHM'),
    ('The Phoenix Mills Limite.rolling.12D', 'PHOENIXLTD'),
    ('TITAN.rolling.12D', 'TITAN'),
    ('TORRENT PHARMACEUTICALS.rolling.12D', 'TORNTPHARM'),
    ('TRENT LIMITED.rolling.12D', 'TRENT'),
    ('TUBE INVESTMENTS OF INDI.rolling.12D', 'TIINDIA'),
    ('TVS MOTOR COMPANY LIMITE.rolling.12D', 'TVSMOTOR'),
    ('ULTRATECH CEMENT LIMITED.rolling.12D', 'ULTRACEMCO'),
    ('UNION BANK OF INDIA.rolling.12D', 'UNIONBANK'),
    ('UNITDSPR.rolling.12D', 'UNITDSPR'),
    ('UNO Minda Limited.rolling.12D', 'UNOMINDA'),
    ('UPL Limited.rolling.12D', 'UPL'),
    ('VARUN BEVERAGES LIMITED.rolling.12D', 'VBL'),
    ('Vedanta limited.rolling.12D', 'VEDL'),
    ('VMM.rolling.12D', 'VMM'),
    ('VOLTAS LTD.rolling.12D', 'VOLTAS'),
    ('WAAREEENER.rolling.12D', 'WAAREEENER'),
    ('WIPRO.rolling.12D', 'WIPRO'),
    ('YES BANK LIMITED.rolling.12D', 'YESBANK'),
    ('ZYDUSLIFE.rolling.12D', 'ZYDUSLIFE'),
]

MAIN_COLUMN_NAME_DATA = [
    # Sharekhan columns (C,D,E,F,I,J,K,L,M,N,O,P,Z,AA,AB)
    ("Scrip Name",                    "Scrip Name"),
    ("Lot Size",                      "Lot Size"),
    ("% Change",                      "% Change"),
    ("Current",                       "Current"),
    ("Open",                          "Open"),
    ("High",                          "High"),
    ("Low",                           "Low"),
    ("Close",                         "Close"),
    ("Avg Rate",                      "Avg Rate"),
    ("OI Difference Percentage",      "OI Difference Percentage"),
    ("P.High",                        "P.High"),
    ("P.Low",                         "P.Low"),
    ("Qty",                           "Qty"),
    ("P.Quantity",                    "P.Quantity"),
    ("TurnOver",                      "TurnOver"),
    # ReliableSoftware columns (B,E,F,K,L)
    ("ScripName",                     "ScripName"),
    ("callstrikehighestoi",           "callstrikehighestoi"),
    ("Callstrikewithsecondhighestoi", "Callstrikewithsecondhighestoi"),
    ("PutStrikeWithsecondHighestOI",  "PutStrikeWithsecondHighestOI"),
    ("TodayPutHighestStrike",         "TodayPutHighestStrike"),
    # NiftyInvest columns (A,C)
    ("Symbol",                        "Symbol"),
    ("Max Pain",                      "Max Pain"),
]

MAIN_COLUMN_ORDER_DATA = [
    # Sharekhan
    ("Scrip Name",),
    ("Lot Size",),
    ("% Change",),
    ("Current",),
    ("Open",),
    ("High",),
    ("Low",),
    ("Close",),
    ("Avg Rate",),
    ("OI Difference Percentage",),
    ("P.High",),
    ("P.Low",),
    ("Qty",),
    ("P.Quantity",),
    ("TurnOver",),
    # ReliableSoftware
    ("ScripName",),
    ("callstrikehighestoi",),
    ("Callstrikewithsecondhighestoi",),
    ("PutStrikeWithsecondHighestOI",),
    ("TodayPutHighestStrike",),
    # NiftyInvest
    ("Symbol",),
    ("Max Pain",),
]
